// OAuth provider utilities — Google and GitHub.
//
// Uses Node.js built-in fetch (available since Node 18).
// No external OAuth dependencies — consistent with the rest of this module.
//
// Responsibilities:
//   · Build provider authorization URLs
//   · Exchange authorization codes for access tokens
//   · Fetch normalized user profiles from each provider
//   · Cookie-parsing helper used by callback handlers
//
// CSRF state:
//   The state parameter is generated by the initiation handler and stored in
//   a short-lived HttpOnly cookie.  The callback handler reads the cookie and
//   compares it against the `state` query param — one-time use, 5-minute TTL.
//   In serverless deployments each invocation may run in a different process,
//   so cookie-based state is the only approach that works reliably without a
//   shared cache.

import { randomBytes } from 'node:crypto';

// ── State helpers ──────────────────────────────────────────────────────────────

/**
 * Generate a cryptographically random state token for CSRF protection.
 * @returns {string}  hex string, 48 characters
 */
export function generateState() {
  return randomBytes(24).toString('hex');
}

// ── Cookie helpers ──────────────────────────────────────────────────────────────

/**
 * Parse a raw `Cookie` header value into a key→value object.
 * @param {string|undefined} cookieHeader
 * @returns {Record<string, string>}
 */
export function parseCookies(cookieHeader) {
  if (!cookieHeader) return {};
  return Object.fromEntries(
    cookieHeader.split(';').map(c => {
      const [k, ...v] = c.trim().split('=');
      return [k.trim(), v.join('=')];
    }),
  );
}

// ── Google ─────────────────────────────────────────────────────────────────────

const GOOGLE_AUTH_URL    = 'https://accounts.google.com/o/oauth2/v2/auth';
const GOOGLE_TOKEN_URL   = 'https://oauth2.googleapis.com/token';
const GOOGLE_USERINFO_URL = 'https://www.googleapis.com/oauth2/v3/userinfo';

/**
 * Build the Google OAuth 2.0 authorization URL.
 * @param {string} state        CSRF state token
 * @param {string} clientId     Google OAuth client ID
 * @param {string} redirectUri  Callback URL registered in Google Console
 * @returns {string}
 */
export function buildGoogleAuthUrl(state, clientId, redirectUri) {
  const params = new URLSearchParams({
    client_id:     clientId,
    redirect_uri:  redirectUri,
    response_type: 'code',
    scope:         'openid email profile',
    state,
    access_type:   'online',
    prompt:        'select_account',
  });
  return `${GOOGLE_AUTH_URL}?${params}`;
}

/**
 * Exchange a Google authorization code for tokens.
 * @param {string} code
 * @param {string} clientId
 * @param {string} clientSecret
 * @param {string} redirectUri
 * @returns {Promise<{ access_token: string, id_token?: string, [key: string]: unknown }>}
 */
export async function exchangeGoogleCode(code, clientId, clientSecret, redirectUri) {
  const res = await fetch(GOOGLE_TOKEN_URL, {
    method:  'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body:    new URLSearchParams({
      code,
      client_id:     clientId,
      client_secret: clientSecret,
      redirect_uri:  redirectUri,
      grant_type:    'authorization_code',
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Google token exchange failed (${res.status}): ${text}`);
  }

  return res.json();
}

/**
 * Fetch the authenticated user's Google profile.
 * Returns a normalized { id, email, name } object.
 * @param {string} accessToken
 * @returns {Promise<{ id: string, email: string|null, name: string }>}
 */
export async function fetchGoogleProfile(accessToken) {
  const res = await fetch(GOOGLE_USERINFO_URL, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!res.ok) throw new Error(`Google profile fetch failed (${res.status})`);

  const data = await res.json();

  return {
    id:    data.sub,
    email: data.email ?? null,
    name:  data.name ?? data.email ?? 'Google User',
  };
}

// ── GitHub ─────────────────────────────────────────────────────────────────────

const GITHUB_AUTH_URL     = 'https://github.com/login/oauth/authorize';
const GITHUB_TOKEN_URL    = 'https://github.com/login/oauth/access_token';
const GITHUB_USERINFO_URL = 'https://api.github.com/user';
const GITHUB_EMAILS_URL   = 'https://api.github.com/user/emails';

/**
 * Build the GitHub OAuth authorization URL.
 * @param {string} state
 * @param {string} clientId     GitHub OAuth App client ID
 * @param {string} redirectUri  Callback URL registered in GitHub App settings
 * @returns {string}
 */
export function buildGitHubAuthUrl(state, clientId, redirectUri) {
  const params = new URLSearchParams({
    client_id:    clientId,
    redirect_uri: redirectUri,
    scope:        'read:user user:email',
    state,
  });
  return `${GITHUB_AUTH_URL}?${params}`;
}

/**
 * Exchange a GitHub authorization code for an access token.
 * @param {string} code
 * @param {string} clientId
 * @param {string} clientSecret
 * @param {string} redirectUri
 * @returns {Promise<{ access_token: string, token_type: string, scope: string }>}
 */
export async function exchangeGitHubCode(code, clientId, clientSecret, redirectUri) {
  const res = await fetch(GITHUB_TOKEN_URL, {
    method:  'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Accept':       'application/json',
    },
    body: new URLSearchParams({
      code,
      client_id:     clientId,
      client_secret: clientSecret,
      redirect_uri:  redirectUri,
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub token exchange failed (${res.status}): ${text}`);
  }

  const data = await res.json();

  if (data.error) {
    throw new Error(
      `GitHub token exchange error: ${data.error_description ?? data.error}`,
    );
  }

  return data;
}

/**
 * Fetch the authenticated user's GitHub profile.
 * If the user's email is private, falls back to the /user/emails endpoint.
 * Returns a normalized { id, email, name } object.
 * @param {string} accessToken
 * @returns {Promise<{ id: string, email: string|null, name: string }>}
 */
export async function fetchGitHubProfile(accessToken) {
  const headers = {
    Authorization: `Bearer ${accessToken}`,
    'User-Agent':  'wander-travel-app',
    Accept:        'application/vnd.github+json',
  };

  const res = await fetch(GITHUB_USERINFO_URL, { headers });

  if (!res.ok) throw new Error(`GitHub profile fetch failed (${res.status})`);

  const data = await res.json();

  let email = data.email ?? null;

  // If the email is not public on the profile, try the emails endpoint.
  if (!email) {
    const emailsRes = await fetch(GITHUB_EMAILS_URL, { headers });
    if (emailsRes.ok) {
      const emails = await emailsRes.json();
      const primary = emails.find(e => e.primary && e.verified);
      email = primary?.email ?? emails[0]?.email ?? null;
    }
  }

  return {
    id:    String(data.id),
    email,
    name:  data.name ?? data.login,
  };
}
